-- Additive schema for enterprise admin student management logs.
-- Run this in your Supabase SQL editor.

create table if not exists public.admin_activity_logs (
  id bigint generated by default as identity primary key,
  admin_id uuid not null references auth.users(id) on delete cascade,
  action text not null,
  details text,
  timestamp timestamptz not null default now()
);

create index if not exists idx_admin_activity_logs_admin_id
  on public.admin_activity_logs (admin_id);

create index if not exists idx_admin_activity_logs_timestamp
  on public.admin_activity_logs (timestamp desc);
